# Generated by Django 2.1.8 on 2020-06-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oiaj', models.BooleanField()),
                ('problem_link', models.CharField(max_length=100)),
                ('problem_name', models.CharField(max_length=50)),
                ('problem_points', models.IntegerField()),
                ('solvedBy', models.TextField()),
            ],
        ),
    ]
