# Generated by Django 2.1.8 on 2020-07-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='judge',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='NULL', max_length=50),
        ),
    ]
