# Generated by Django 2.1.8 on 2020-07-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problems_judge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='judge',
            field=models.CharField(choices=[('OIAJ', 'OIAJ'), ('Codeforces', 'Codeforces'), ('CSES', 'CSES')], default='NULL', max_length=50),
        ),
    ]
