# Generated by Django 2.1.8 on 2020-07-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20200714_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='oiaj',
        ),
    ]
