# Generated by Django 2.1.8 on 2020-08-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20200801_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='problem_link',
            field=models.CharField(max_length=500),
        ),
    ]
