# Generated by Django 2.1.8 on 2020-06-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recommended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oiaj', models.BooleanField()),
                ('problem_link', models.CharField(max_length=100)),
                ('problem_name', models.CharField(max_length=50)),
                ('solvedBy', models.TextField()),
                ('proposedBy', models.CharField(choices=[('OIAJ', 'OIAJ'), ('Codeforces', 'Codeforces')], max_length=30)),
            ],
        ),
    ]
