# Generated by Django 2.1.8 on 2020-06-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommended',
            name='oiaj',
            field=models.CharField(choices=[('OIAJ', 'OIAJ'), ('Codeforces', 'Codeforces')], max_length=30),
        ),
        migrations.AlterField(
            model_name='recommended',
            name='proposedBy',
            field=models.CharField(max_length=30),
        ),
    ]
