# Generated by Django 2.1.8 on 2020-06-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended', '0003_auto_20200627_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommended',
            name='judge',
            field=models.BooleanField(),
        ),
    ]
