# Generated by Django 2.1.8 on 2020-06-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommended', '0004_auto_20200627_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommended',
            old_name='judge',
            new_name='oiaj',
        ),
    ]
