# Generated by Django 2.1.8 on 2020-06-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommended', '0005_auto_20200627_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommended',
            name='proposedBy',
        ),
    ]
