# Generated by Django 2.1.8 on 2020-07-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended', '0006_remove_recommended_proposedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommended',
            name='oiaj',
        ),
        migrations.AddField(
            model_name='recommended',
            name='judge',
            field=models.CharField(choices=[('OIAJ', 'OIAJ'), ('Codeforces', 'Codeforces'), ('CSES', 'CSES')], default='CSES', max_length=50),
        ),
    ]
