# Generated by Django 2.1.8 on 2020-08-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended', '0007_auto_20200718_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommended',
            name='judge',
            field=models.CharField(choices=[('OIAJ', 'OIAJ'), ('Codeforces', 'Codeforces'), ('CSES', 'CSES'), ('SPOJ', 'SPOJ')], default='CSES', max_length=50),
        ),
    ]
