# Generated by Django 2.1.8 on 2020-08-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended', '0008_auto_20200801_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommended',
            name='problem_link',
            field=models.CharField(max_length=500),
        ),
    ]
