# Generated by Django 2.1.8 on 2020-08-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended', '0009_auto_20200802_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommended',
            name='judge',
            field=models.CharField(choices=[('OIAJ', 'OIAJ'), ('Codeforces', 'Codeforces'), ('CSES', 'CSES'), ('SPOJ', 'SPOJ'), ('OnlineJudge', 'OnlineJudge')], default='CSES', max_length=50),
        ),
    ]
