# Generated by Django 2.1.8 on 2020-07-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=50)),
                ('contest_length', models.IntegerField()),
                ('contest_problems', models.TextField()),
            ],
        ),
    ]
