# Generated by Django 3.1.7 on 2021-02-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountID', models.IntegerField()),
                ('Logik_Handle', models.CharField(blank=True, max_length=30, null=True)),
                ('CF_Handle', models.CharField(blank=True, max_length=30, null=True)),
                ('OIAJ_Handle', models.CharField(blank=True, max_length=30, null=True)),
                ('CSES_Handle', models.IntegerField(blank=True, null=True)),
                ('SPOJ_Handle', models.CharField(blank=True, max_length=30, null=True)),
                ('OnlineJudge_Handle', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_user', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge', models.CharField(choices=[('OIAJ', 'OIAJ'), ('Codeforces', 'Codeforces'), ('CSES', 'CSES'), ('SPOJ', 'SPOJ'), ('OnlineJudge', 'OnlineJudge')], default='CSES', max_length=50)),
                ('problem_link', models.CharField(max_length=500)),
                ('problem_name', models.CharField(max_length=50)),
                ('problem_points', models.IntegerField()),
                ('solvedBy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='recommended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge', models.CharField(choices=[('OIAJ', 'OIAJ'), ('Codeforces', 'Codeforces'), ('CSES', 'CSES'), ('SPOJ', 'SPOJ'), ('OnlineJudge', 'OnlineJudge')], default='CSES', max_length=50)),
                ('problem_link', models.CharField(max_length=500)),
                ('problem_name', models.CharField(max_length=50)),
                ('solvedBy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id_tutorial', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('autor', models.TextField()),
                ('cuerpo', models.TextField()),
                ('likes', models.IntegerField()),
                ('comentarios', models.TextField()),
            ],
        ),
    ]
