# Generated by Django 3.1.4 on 2021-05-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
