# Generated by Django 3.1.4 on 2021-05-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=500)),
                ('problem_points', models.IntegerField()),
                ('problem_link', models.CharField(max_length=500)),
                ('puntaje', models.IntegerField()),
                ('color', models.CharField(max_length=500)),
                ('cantidadAC', models.IntegerField()),
                ('cantidadIntentos', models.IntegerField()),
            ],
        ),
    ]
