# Generated by Django 3.1.4 on 2021-05-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_problemitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='problemitem',
            old_name='cantidadAC',
            new_name='accepted_submissions',
        ),
        migrations.RenameField(
            model_name='problemitem',
            old_name='cantidadIntentos',
            new_name='attempts_number',
        ),
        migrations.RenameField(
            model_name='problemitem',
            old_name='problem_points',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='problemitem',
            old_name='puntaje',
            new_name='user_points',
        ),
        migrations.RemoveField(
            model_name='problemitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='problemitem',
            name='problem_name',
        ),
        migrations.AlterField(
            model_name='problemitem',
            name='problem_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.problemlink'),
        ),
    ]
