# Generated by Django 3.1.4 on 2021-05-10 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210510_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemitem',
            name='problem_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_link', to='app.problemlink'),
        ),
    ]
