# Generated by Django 3.1.4 on 2021-05-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210510_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemitem',
            name='problem_link',
        ),
    ]
