# Generated by Django 3.1.4 on 2021-05-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_problemitem_problem_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProblemItem',
        ),
        migrations.DeleteModel(
            name='ProblemLink',
        ),
    ]
