# Generated by Django 3.1.4 on 2021-05-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210510_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('points', models.IntegerField()),
                ('link', models.CharField(max_length=500)),
                ('user_points', models.IntegerField()),
                ('accepted_submissions', models.IntegerField()),
                ('attempts_number', models.IntegerField()),
            ],
        ),
    ]
