# Generated by Django 3.1.4 on 2021-05-11 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_problemitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemitem',
            old_name='accepted_submissions',
            new_name='acceptance',
        ),
        migrations.RemoveField(
            model_name='problemitem',
            name='attempts_number',
        ),
        migrations.RemoveField(
            model_name='problemitem',
            name='points',
        ),
    ]
