# Generated by Django 3.1.4 on 2021-05-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210511_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('score', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='problemitem',
            name='user_points',
            field=models.FloatField(),
        ),
    ]
