# Generated by Django 3.1.4 on 2021-05-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210512_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemitem',
            old_name='user_points',
            new_name='score',
        ),
    ]
