# Generated by Django 3.1.2 on 2020-10-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id_tutorial', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('autor', models.TextField()),
                ('cuerpo', models.TextField()),
                ('likes', models.IntegerField()),
                ('comentarios', models.IntegerField()),
            ],
        ),
    ]
