# Generated by Django 3.1.2 on 2020-10-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='comentarios',
            field=models.TextField(),
        ),
    ]
