# Generated by Django 3.0.7 on 2020-06-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountID', models.IntegerField()),
                ('CF_Handle', models.CharField(blank=True, max_length=30, null=True)),
                ('OIAJ_Handle', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
