# Generated by Django 2.1.8 on 2020-06-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Logik_Handle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
