# Generated by Django 2.1.8 on 2020-07-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_logik_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='CSES_Handle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
