# Generated by Django 2.1.8 on 2020-07-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_cses_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='CSES_Handle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
