# Generated by Django 2.1.8 on 2020-07-22 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200719_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='City',
        ),
        migrations.RemoveField(
            model_name='account',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Province',
        ),
        migrations.RemoveField(
            model_name='account',
            name='School',
        ),
    ]
