# Generated by Django 2.1.8 on 2020-08-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200722_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='SPOJ_Handle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
