# Generated by Django 2.1.8 on 2020-08-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_spoj_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='SPOJ_Handle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
