# Generated by Django 2.1.8 on 2020-08-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_onlinejudge_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='OnlineJudge_Handle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
